import dynamic from 'next/dynamic';
import Head from 'next/head';
import Image from 'next/image';
import DetailCard from '../components/DetailCard';
// import BarCharts from '../components/BarCharts';
import Footer from '../components/Footer';
import styles from '../styles/Home.module.css';
import trendsData from '../data/Data_GT.json';
import trendsDataSDGs from '../data/Data_SDGs.json';
import SearchBar from '../components/SearchBar';
import Navbar from '../components/Navbar';
import SectorDropDown from '../components/SectorDropDown';
import SectorButton from '../components/SectorButton';

const BarCharts = dynamic(() => import('../components/BarCharts'), {
  ssr: false,
});

export default function Home() {
  const positiveSectorTrendSorted = Object.keys(trendsData)
    .filter((sector) => trendsData[sector]['combined_trends_mean_change'] > 0.0)
    .sort(
      (a, b) =>
        -(
          trendsData[a]['combined_trends_mean_change'] -
          trendsData[b]['combined_trends_mean_change']
        )
    );

  const positiveSectorTrendSortedData = positiveSectorTrendSorted.map(
    (sector) => trendsData[sector]['combined_trends_mean_change']
  );

  const negativeSectorTrendSorted = Object.keys(trendsData)
    .filter((sector) => trendsData[sector]['combined_trends_mean_change'] < 0.0)
    .sort(
      (a, b) =>
        -(
          trendsData[a]['combined_trends_mean_change'] -
          trendsData[b]['combined_trends_mean_change']
        )
    );

  const negativeSectorTrendSortedData = negativeSectorTrendSorted.map(
    (sector) => trendsData[sector]['combined_trends_mean_change']
  );

  const trendsDataSorted = Object.keys(trendsData).sort(
    (a, b) =>
      -(
        trendsData[a]['combined_trends_mean_change'] -
        trendsData[b]['combined_trends_mean_change']
      )
  );
  const trendsDataSDGsSorted = Object.keys(trendsDataSDGs).sort(
    (a, b) =>
      -(
        trendsDataSDGs[a]['combined_trends_mean_change'] -
        trendsDataSDGs[b]['combined_trends_mean_change']
      )
  );

  return (
    // <div>
    //   <Head>
    //     <title>Create Next App</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>
    //   <h1>Hello World</h1>
    // </div>
    <div className="min-h-screen bg-white">
      {/* <SectorDropDown /> */}
      <Navbar />
      <div className="flex-1 max-w-7xl mx-auto p-10">
        <section className="my-16">
          <h1 className="text-black text-[1.5rem] font-bold text-center max-w-2xl m-auto">
            Ingin mengetahui topik apa yang banyak ditelusuri masyarakat pada
            google pada setiap sektor? Yuk cari!
          </h1>
          <SearchBar />
        </section>
        <section className="my-16">
          <h1 className="text-black text-[1.5rem] font-bold text-center max-w-2xl m-auto">
            Topik Trending
          </h1>
          <div className="flex flex-wrap justify-center">
            <SectorButton name="Kesehatan" />
            <SectorButton name="Kesehatan" />
            <SectorButton name="Kesehatan" />
            <SectorButton name="Kesehatan" />
            <SectorButton name="Kesehatan" />
            <SectorButton name="Kesehatan" />
            <SectorButton name="Kesehatan" />
            <SectorButton name="Kesehatan" />
            <SectorButton name="Kesehatan" />
            <SectorButton name="Kesehatan" />
            <SectorButton name="Kesehatan" />
            <SectorButton name="Kesehatan" />
            <SectorButton name="Kesehatan" />
          </div>
        </section>

        <section className="my-16">
          <h1 className="text-black text-[2rem] font-bold">
            Lorem ipsum dolor sit amet consectetur adipisicing elit.
          </h1>
          <p className="text-black text-[1.1rem]">
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ad, ullam
            officia optio numquam voluptatibus tenetur similique eveniet
            repudiandae voluptate eum autem atque nesciunt, aspernatur fugiat
            dolore, magni explicabo beatae. Aperiam.
          </p>
        </section>
        <section className="my-16">
          <h1 className="text-black text-[2rem] font-bold">
            Lorem ipsum dolor sit amet consectetur adipisicing elit.
          </h1>
          <p className="text-black text-[1.1rem]">
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ad, ullam
            officia optio numquam voluptatibus tenetur similique eveniet
            repudiandae voluptate eum autem atque nesciunt, aspernatur fugiat
            dolore, magni explicabo beatae. Aperiam.
          </p>
          <BarCharts
            sector={positiveSectorTrendSorted.map(
              (sector) => trendsData[sector]['name']
            )}
            series={positiveSectorTrendSortedData}
            fillColor="#07818F"
          />
        </section>
        <section className="my-16">
          <h1 className="text-black text-[2rem] font-bold">
            Lorem ipsum dolor sit amet consectetur adipisicing elit.
          </h1>
          <p className="text-black text-[1.1rem]">
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ad, ullam
            officia optio numquam voluptatibus tenetur similique eveniet
            repudiandae voluptate eum autem atque nesciunt, aspernatur fugiat
            dolore, magni explicabo beatae. Aperiam.
            <BarCharts
              sector={negativeSectorTrendSorted.map(
                (sector) => trendsData[sector]['name']
              )}
              series={negativeSectorTrendSortedData}
              fillColor="#DA127D"
            />
          </p>
        </section>
        <h1 className="text-black text-[2rem] font-bold">
          Klik untuk melihat lebih detail
        </h1>
        <ul className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-8">
          {trendsDataSorted.map((k, index) => {
            return (
              <>
                <li key={index}>
                  <DetailCard
                    href={`/sector/${encodeURIComponent(k)}`}
                    sector={trendsData[k]['name']}
                    trendsChange={trendsData[k]['combined_trends_mean_change']}
                  />
                </li>
              </>
            );
          })}
          {/* <li>
            <DetailCard sector = "India"/>
          </li>
          <li>
            <DetailCard />
          </li>
          <li>
            <DetailCard />
          </li>
          <li>
            <DetailCard />
          </li>
          <li>
            <DetailCard />
          </li>
          <li>
            <DetailCard />
          </li>
          <li>
            <DetailCard />
          </li>
          <li>
            <DetailCard />
          </li> */}
        </ul>
        <h1 className="text-black text-[2rem] font-bold">SDGs</h1>
        <ul className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-8">
          {trendsDataSDGsSorted.map((k, index) => {
            return (
              <>
                <li key={index}>
                  <DetailCard
                    href={`/sdgs/${encodeURIComponent(k)}`}
                    sector={trendsDataSDGs[k]['name']}
                    trendsChange={
                      trendsDataSDGs[k]['combined_trends_mean_change']
                    }
                  />
                </li>
              </>
            );
          })}
        </ul>
        {/* <hr className="mt-10 border-[#555]" /> */}
      </div>
      <Footer />
    </div>
  );
}
